// <auto-generated />
using System;
using MedicalServices.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalServices.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250422191324_RemoveDoctorScheduleTable")]
    partial class RemoveDoctorScheduleTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalServices.Models.AvailableAppointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<TimeOnly>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("AvailableAppointments");
                });

            modelBuilder.Entity("MedicalServices.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Age")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("ForHimSelf")
                        .HasColumnType("bit");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("MedicalServices.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("MedicalServices.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Focus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Heart St",
                            Experience = "10 years",
                            Gender = 0,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Pulse Ave",
                            Experience = "8 years",
                            Gender = 1,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Artery Blvd",
                            Experience = "12 years",
                            Gender = 0,
                            SpecializationId = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Skin Lane",
                            Experience = "7 years",
                            Gender = 1,
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Acne Dr",
                            Experience = "6 years",
                            Gender = 0,
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Derma Ct",
                            Experience = "9 years",
                            Gender = 1,
                            SpecializationId = 2
                        },
                        new
                        {
                            Id = 7,
                            Address = "123 Brain Ave",
                            Experience = "15 years",
                            Gender = 0,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 8,
                            Address = "456 Neuron Blvd",
                            Experience = "11 years",
                            Gender = 1,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 9,
                            Address = "789 Spine Dr",
                            Experience = "13 years",
                            Gender = 0,
                            SpecializationId = 3
                        },
                        new
                        {
                            Id = 10,
                            Address = "321 Bone St",
                            Experience = "14 years",
                            Gender = 0,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 11,
                            Address = "654 Joint Ave",
                            Experience = "8 years",
                            Gender = 1,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 12,
                            Address = "987 Fracture Rd",
                            Experience = "10 years",
                            Gender = 0,
                            SpecializationId = 4
                        },
                        new
                        {
                            Id = 13,
                            Address = "123 Kids Ln",
                            Experience = "5 years",
                            Gender = 1,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 14,
                            Address = "456 Baby Blvd",
                            Experience = "6 years",
                            Gender = 0,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 15,
                            Address = "789 Child Ct",
                            Experience = "8 years",
                            Gender = 1,
                            SpecializationId = 5
                        },
                        new
                        {
                            Id = 16,
                            Address = "321 Cancer St",
                            Experience = "12 years",
                            Gender = 0,
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 17,
                            Address = "654 Tumor Blvd",
                            Experience = "10 years",
                            Gender = 1,
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 18,
                            Address = "987 Chemo Rd",
                            Experience = "11 years",
                            Gender = 0,
                            SpecializationId = 6
                        },
                        new
                        {
                            Id = 19,
                            Address = "123 Mind St",
                            Experience = "9 years",
                            Gender = 1,
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 20,
                            Address = "456 Emotion Ave",
                            Experience = "8 years",
                            Gender = 0,
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 21,
                            Address = "789 Therapy Ct",
                            Experience = "7 years",
                            Gender = 1,
                            SpecializationId = 7
                        },
                        new
                        {
                            Id = 22,
                            Address = "321 Xray Ln",
                            Experience = "13 years",
                            Gender = 0,
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 23,
                            Address = "654 MRI Blvd",
                            Experience = "12 years",
                            Gender = 1,
                            SpecializationId = 8
                        },
                        new
                        {
                            Id = 24,
                            Address = "987 CT Scan Rd",
                            Experience = "14 years",
                            Gender = 0,
                            SpecializationId = 8
                        });
                });

            modelBuilder.Entity("MedicalServices.Models.Identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("MedicalServices.Models.Identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a22134cc-f36c-486f-9e23-671b146e7efd",
                            Email = "john.smith@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. John Smith",
                            Password = "hashed_password_123",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.john.smith"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3e0d93a9-0374-4edc-a006-8febeb1cab18",
                            Email = "sarah.johnson@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Sarah Johnson",
                            Password = "hashed_password_456",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.sarah.johnson"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "48f38141-c917-43b6-90b6-80e95e17729e",
                            Email = "ahmed.ali@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Ahmed Ali",
                            Password = "hashed_password_789",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.ahmed.ali"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "02aca8ad-6847-47b5-8d8e-2faa5e61b8fe",
                            Email = "emily.brown@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Emily Brown",
                            Password = "hashed_password_101",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.emily.brown"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "69a3f8db-89c4-42f3-83f4-ca2d68ecd760",
                            Email = "william.davis@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. William Davis",
                            Password = "hashed_password_102",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.william.davis"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14677a51-97a3-4fcb-90f5-6d095199ac70",
                            Email = "fatima.hassan@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Fatima Hassan",
                            Password = "hashed_password_103",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.fatima.hassan"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "487ccf26-fdfa-4bb5-827e-5be1dee9d680",
                            Email = "jacob.wilson@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Jacob Wilson",
                            Password = "hashed_password_104",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.jacob.wilson"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c48f06e9-c540-42e0-b8fc-f7c3248aade8",
                            Email = "sophia.martinez@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Sophia Martinez",
                            Password = "hashed_password_105",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.sophia.martinez"
                        },
                        new
                        {
                            Id = 9,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d5396e55-5151-497d-9d33-53539154a766",
                            Email = "ethan.thompson@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Ethan Thompson",
                            Password = "hashed_password_106",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.ethan.thompson"
                        },
                        new
                        {
                            Id = 10,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8989ca6f-fc1c-4100-b46f-6b52b20c6050",
                            Email = "ava.garcia@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Ava Garcia",
                            Password = "hashed_password_107",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.ava.garcia"
                        },
                        new
                        {
                            Id = 11,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8fae64f7-1f81-4f90-831b-12bd1103ecb2",
                            Email = "michael.lee@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Michael Lee",
                            Password = "hashed_password_108",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.michael.lee"
                        },
                        new
                        {
                            Id = 12,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "14d6e854-bc1c-4f22-981e-98eb5626a422",
                            Email = "olivia.rodriguez@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Olivia Rodriguez",
                            Password = "hashed_password_109",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.olivia.rodriguez"
                        },
                        new
                        {
                            Id = 13,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8eb5565c-65bc-4b68-b83b-c433d965637a",
                            Email = "benjamin.white@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Benjamin White",
                            Password = "hashed_password_110",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.benjamin.white"
                        },
                        new
                        {
                            Id = 14,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f75d88b7-094c-4bd7-9549-4cf906dfdffb",
                            Email = "isabella.hall@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Isabella Hall",
                            Password = "hashed_password_111",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.isabella.hall"
                        },
                        new
                        {
                            Id = 15,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0406d8ba-992d-45f5-a3d6-17d12b5456e9",
                            Email = "daniel.young@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Daniel Young",
                            Password = "hashed_password_112",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.daniel.young"
                        },
                        new
                        {
                            Id = 16,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e53e057-6ff5-408d-b0d9-574af057f465",
                            Email = "mia.king@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Mia King",
                            Password = "hashed_password_113",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.mia.king"
                        },
                        new
                        {
                            Id = 17,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0fe5dc0-923c-4f34-bac4-a0fc74b08a1d",
                            Email = "james.wright@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. James Wright",
                            Password = "hashed_password_114",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.james.wright"
                        },
                        new
                        {
                            Id = 18,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "719f794a-9d4f-4c58-88e7-2caf378ea7a9",
                            Email = "amelia.scott@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Amelia Scott",
                            Password = "hashed_password_115",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.amelia.scott"
                        },
                        new
                        {
                            Id = 19,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0ee4eb4-08f2-46b0-a02f-c75fe5ef2c51",
                            Email = "lucas.green@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Lucas Green",
                            Password = "hashed_password_116",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.lucas.green"
                        },
                        new
                        {
                            Id = 20,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "142eb2ca-804c-4716-9ae4-8b61cf606c9b",
                            Email = "charlotte.adams@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Charlotte Adams",
                            Password = "hashed_password_117",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.charlotte.adams"
                        },
                        new
                        {
                            Id = 21,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b36e0b12-f3b8-4814-88ce-d28c76efb1e0",
                            Email = "henry.baker@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Henry Baker",
                            Password = "hashed_password_118",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.henry.baker"
                        },
                        new
                        {
                            Id = 22,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "acbac847-c97f-4c30-87bf-614fff8a3d0f",
                            Email = "grace.nelson@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Grace Nelson",
                            Password = "hashed_password_119",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.grace.nelson"
                        },
                        new
                        {
                            Id = 23,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e32a4a7a-c244-4557-80c9-e36844f3b5fa",
                            Email = "elijah.carter@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Elijah Carter",
                            Password = "hashed_password_120",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.elijah.carter"
                        },
                        new
                        {
                            Id = 24,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "15970238-c98c-4fb7-8a76-876111aed72f",
                            Email = "lily.mitchell@hospital.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Dr. Lily Mitchell",
                            Password = "hashed_password_121",
                            PhoneNumberConfirmed = false,
                            RoleId = 0,
                            TwoFactorEnabled = false,
                            UserName = "dr.lily.mitchell"
                        });
                });

            modelBuilder.Entity("MedicalServices.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("MedicalServices.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treatment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("MedicalServices.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("SenderType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("MedicalServices.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("MedicalServices.Models.PatientFavoriteDoctors", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("PatientId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("PatientFavoriteDoctors");
                });

            modelBuilder.Entity("MedicalServices.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MedicalServices.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MedicalServices.Models.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Oncology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Psychiatry"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Radiology"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedicalServices.Models.AvailableAppointments", b =>
                {
                    b.HasOne("MedicalServices.Models.Doctor", "Doctor")
                        .WithMany("AvailableAppointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalServices.Models.Booking", b =>
                {
                    b.HasOne("MedicalServices.Models.AvailableAppointments", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Doctor", "Doctor")
                        .WithMany("Bookings")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Patient", "Patient")
                        .WithMany("Bookings")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalServices.Models.Doctor", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", "User")
                        .WithOne("Doctor")
                        .HasForeignKey("MedicalServices.Models.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Specialization", "Specialization")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalServices.Models.MedicalRecord", b =>
                {
                    b.HasOne("MedicalServices.Models.Booking", "Booking")
                        .WithOne("MedicalRecord")
                        .HasForeignKey("MedicalServices.Models.MedicalRecord", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MedicalServices.Models.Notification", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", null)
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("MedicalServices.Models.Patient", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", "User")
                        .WithOne("Patient")
                        .HasForeignKey("MedicalServices.Models.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicalServices.Models.PatientFavoriteDoctors", b =>
                {
                    b.HasOne("MedicalServices.Models.Doctor", "Doctor")
                        .WithMany("PatientFavoriteDoctors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Patient", "patient")
                        .WithMany("PatientFavoriteDoctors")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("MedicalServices.Models.Payment", b =>
                {
                    b.HasOne("MedicalServices.Models.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("MedicalServices.Models.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("MedicalServices.Models.Review", b =>
                {
                    b.HasOne("MedicalServices.Models.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Patient", "Patient")
                        .WithMany("Reviews")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalServices.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("MedicalServices.Models.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalServices.Models.Booking", b =>
                {
                    b.Navigation("MedicalRecord")
                        .IsRequired();

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalServices.Models.Doctor", b =>
                {
                    b.Navigation("AvailableAppointments");

                    b.Navigation("Bookings");

                    b.Navigation("PatientFavoriteDoctors");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MedicalServices.Models.Identity.User", b =>
                {
                    b.Navigation("Doctor")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("Patient")
                        .IsRequired();
                });

            modelBuilder.Entity("MedicalServices.Models.Patient", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PatientFavoriteDoctors");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MedicalServices.Models.Specialization", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
